version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:10-master'
    ports:
      - '5432:5432'
    volumes:
      - ./data:/bitnami
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=viny
